### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by JerimSD** [2muchcoffeecom/ngx-restangular#167]
Hi!

I just upgraded a project I'm working on to Angular 8.0.0 and I get this message :

> ERROR in node_modules/ngx-restangular/lib/ngx-restangular-http.d.ts(3,27): error TS2307: Cannot find module '@angular/common/http/src/response'.

It seems restangular doesn't support Angular 8 yet, is it a work in progress ?

**Comment by JerimSD** [comment]
Duplicate of #165 
Sorry
