### ISSUE TITLE
How do I add this to my project in angular 6?

### ISSUE THREAD

**Issue by andrejkaurin** [2muchcoffeecom/ngx-restangular#140]
In Angular 6 I am getting
ERROR in node_modules/ngx-restangular/src/ngx-restangular-http.d.ts(2,10): error TS2305: Module '"/Users/andrejkaurin/Apps/gpx/gpx-ui/client/node_modules/rxjs/Observable"' has no exported member 'Observable'.

ngx-restangular version: "2.3.0-beta.3"
"@angular/cli": "6.0.3"
"typescript": "2.7.2",

**Comment by hijamoya** [comment]
Please update to support angular6

**Comment by wambowams** [comment]
Anyone know a way to use this in Angular 6 without an update?

**Comment by ghost** [comment]
Guys it is doing great job with angular 6, you can follow this steps to get correct.

$ npm install --save ngx-restangular
Import the restangular module into your app root module

import { RestangularModule } from 'ngx-restangular';

Now, add the module to import list of @NgModule decorator
imports = [
....
RestangularModule.forRoot(restangularConfigFactory)
....
]
Place the below code in app root module

export function restangularConfigFactory(RestangularProvider){
RestangularProvider.setBaseUrl("server address");
}

Now you can use anywhere in other components by doing dependency injection of Restangular

**Comment by iCodr8** [comment]
Works with version `3.0.0`
