### ISSUE TITLE
Error: defineProperty is not a function | ngx-restangular v1.0.11

### ISSUE THREAD

**Issue by cadin81** [2muchcoffeecom/ngx-restangular#85]
Hello!

I'm using ngx-restangular v1.0.10 without a problem on my project, but when I upgrade to v1.0.11 I get the following error. Is there some kind of different configuration for the new version?

```
systemjs.run.js:6 Error: defineProperty is not a function
  Evaluating http://localhost:8080/node_modules/lodash/assignInWith.js
  Evaluating http://localhost:8080/node_modules/lodash/defaults.js
  Loading main.ts
    at baseSetToString (_baseSetToString.js:14)
    at eval (_shortOut.js:33)
    at baseRest (_baseRest.js:14)
    at createAssigner (_createAssigner.js:12)
    at Object.eval (assignInWith.js:34)
    at eval (assignInWith.js:40)
    at eval (assignInWith.js:41)
    at eval (<anonymous>)
    at Re (system.js:4)
    at system.js:4
handle @ systemjs.run.js:6
e.invoke @ zone.min.js:1
r.run @ zone.min.js:1
(anonymous) @ zone.min.js:1
e.invokeTask @ zone.min.js:1
r.runTask @ zone.min.js:1
o @ zone.min.js:1
```

**Comment by logvinoleg89** [comment]
@cadin81 In the v1.0.11 we were solving the problem discussed in issue #69. Could you please provide more details on the current issue?
